<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KeywordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Keyword::truncate();

        $mobile_keywords = [
            'home' => ['en' => 'Home', 'ar' => 'الرئيسية'],
            'my_channal' => ['en' => 'My Channel', 'ar' => 'قناتي'],
            'love' => ['en' => 'Favorites', 'ar' => 'المفضلة'],
            'edit_profile' => ['en' => 'Edit Profile', 'ar' => 'تعديل الملف الشخصي'],
            'change_pass' => ['en' => 'Change Password', 'ar' => 'تغيير كلمة المرور'],
            'contact_us' => ['en' => 'Contact Us', 'ar' => 'تواصل معنا'],
            'about_us' => ['en' => 'About Us', 'ar' => 'من نحن'],
            'privacy' => ['en' => 'Privacy Policy', 'ar' => 'سياسة الخصوصية'],
            'terms' => ['en' => 'Terms and Conditions', 'ar' => 'الشروط والأحكام'],
            'logout' => ['en' => 'Logout', 'ar' => 'تسجيل الخروج'],
            'Already_have_an_account' => ['en' => 'Already have an account?', 'ar' => 'امتلك حساب بالفعل'],
            'Create_a_new_account' => ['en' => 'Create a new account', 'ar' => 'إنشاء حساب جديد'],
            'Login' => ['en' => 'Login', 'ar' => 'تسجيل الدخول'],
            'Write_short_note_about_yourself' => ['en' => 'Write a short note about yourself', 'ar' => 'اكتب نبذة صغيرة عنك'],
            'I_agree_to' => ['en' => 'I agree to ', 'ar' => 'أوافق على '],
            'Enter_your_password' => ['en' => 'Enter your password', 'ar' => 'أدخل كلمة المرور'],
            'Confirm_password' => ['en' => 'Confirm password', 'ar' => 'تأكيد كلمة المرور'],
            'Choose_your_section' => ['en' => 'Choose your section', 'ar' => 'اختر القسم الخاص بك'],
            'phone_number' => ['en' => 'Enter your phone number', 'ar' => 'ادخل رقم الجوال'],
            'email' => ['en' => 'Enter your email', 'ar' => 'أدخل البريد الإلكتروني'],
            'name' => ['en' => 'Enter your full name', 'ar' => 'أدخل اسمك بالكامل'],
            'Register_now' => ['en' => 'Register Now', 'ar' => 'وسجل الآن'],
            'As_a_content_creator' => ['en' => 'As a content creator', 'ar' => 'كصانع محتوى'],
            'Post_all_your_ideas' => ['en' => 'Post all your ideas', 'ar' => 'انشر جميع أفكارك'],
            'final_step' => ['en' => 'Final Step', 'ar' => 'الخطوة الأخيرة'],
            'final_step1' => ['en' => 'Enter your new password for your account', 'ar' => 'ادخل كلمة المرور الجديدة لحسابك'],
            'newPassword' => ['en' => 'Enter new password', 'ar' => 'أدخل كلمة المرور الجديدة'],
            'reNewPassword' => ['en' => 'Re-enter new password', 'ar' => 'أعد إدخال كلمة المرور الجديدة'],
            'dontWorry' => ['en' => 'Don’t worry, we’ll help you recover your account', 'ar' => 'لا تقلق سنساعدك على إسترجاع حسابك'],
            'enterEmail' => ['en' => 'Enter the email registered with your account to send a verification code', 'ar' => 'أدخل البريد الإلكتروني المسجل بحسابك لإرسال رمز التحقق عليه'],
            'next' => ['en' => 'Next', 'ar' => 'التالي'],
            'forgetPassword' => ['en' => 'Forgot Password', 'ar' => 'نسيت كلمة المرور'],
            'enter_otp' => ['en' => 'Verification Code', 'ar' => 'رمز التحقق'],
            'otpSended' => ['en' => 'Check your code', 'ar' => 'تفقد الرمز'],
            'enterOtp' => ['en' => 'Please enter the verification code sent to you', 'ar' => 'من فضلك أدخل رمز التحقق المرسل إليك'],
            'saveNewPassword' => ['en' => 'Confirm new password', 'ar' => 'تأكيد كلمة المرور الجديدة'],
            'Write_your_message_here' => ['en' => 'Write your message here', 'ar' => 'اكتب رسالتك هنا'],
            'Send_message' => ['en' => 'Send Message', 'ar' => 'إرسال الرسالة'],
            'save' => ['en' => 'Save', 'ar' => 'حفظ'],
            'channals' => ['en' => 'Channels', 'ar' => 'القنوات'],
            'Search' => ['en' => 'Search', 'ar' => 'بحث'],
            'Choose_the_season' => ['en' => 'Choose the season', 'ar' => 'اختر الموسم'],
            'for_add_podcast' => ['en' => 'To add an image to the podcast', 'ar' => 'لإضافة صورة للبودكاست'],
            'add_podcast' => ['en' => 'Add Podcast', 'ar' => 'إضافة البودكاست'],
            'Enter_the_name_of_the_podcast' => ['en' => 'Enter the name of the podcast', 'ar' => 'أدخل اسم البودكاست'],
            'Write_description_podcast' => ['en' => 'Write a brief description of the podcast', 'ar' => 'اكتب وصف مختصر للبودكاست'],
            'Enter_video_link' => ['en' => 'Enter video link', 'ar' => 'أدخل رابط الفيديو'],
            'enter_here' => ['en' => 'Enter here', 'ar' => 'اضغط هنا'],
            'Enter_the_channel_name' => ['en' => 'Enter the channel name', 'ar' => 'أدخل اسم القناة'],
            'Add_video_podcast' => ['en' => 'Add Video Podcast', 'ar' => 'إضافة بودكاست فيديو'],
            'Add_an_audio_podcast' => ['en' => 'Add Audio Podcast', 'ar' => 'إضافة بودكاست صوتي'],
            'To_upload_the_audio_file_of_the_podcast' => ['en' => 'To upload the audio file of the podcast', 'ar' => 'لرفع الملف الصوتي للبودكاست'],
            'You_havennot_done_the_channel_yet' => ['en' => 'You have not created the channel yet', 'ar' => 'أنت لم تفعل بعد القناة'],
            'Write_short_description_channel' => ['en' => 'Write a brief description of the channel', 'ar' => 'اكتب وصف مختصر للقناة'],
            'To_add_picture_channel' => ['en' => 'To add a picture to the channel', 'ar' => 'لإضافة صورة للقناة'],
            'You_havennot_done_the_channel_yet2' => ['en' => 'You can now create it by clicking on Create Channel, then you can add seasons and podcasts to your channel', 'ar' => 'يمكنك الآن إنشائها عبر الضغط على إنشاء قناة، وبعد ذلك يمكنك إضافة المواسم والبودكاست الخاصين بقناتك'],
            'Create_channel' => ['en' => 'Create Channel', 'ar' => 'إنشاء قناة'],
            'Seasons' => ['en' => 'Seasons', 'ar' => 'المواسم'],
            'Season' => ['en' => 'Season', 'ar' => 'مواسم'],
            'podcasts' => ['en' => 'Podcasts', 'ar' => 'بودكسات'],
            'notification' => ['en' => 'Notifications', 'ar' => 'الإشعارات'],
            'problem_with_Internet' => ['en' => 'There is a problem with the internet!', 'ar' => 'يوجد مشكلة في الإنترنت !'],
            'problem_with_Internet2' => ['en' => 'Please check if Wi-Fi or mobile data is enabled', 'ar' => 'تأكد من تفعيل الواي فاي أو بيانات الهاتف'],
            'server_error_1' => ['en' => 'There is a problem with the server!', 'ar' => 'يوجد مشكلة في الخادم !'],
            'server_error_2' => ['en' => 'An error occurred while retrieving information from the server', 'ar' => 'حدث خطأ أثناء استرداد المعلومات من الخادم'],
            'try_agin' => ['en' => 'Try again', 'ar' => 'حاول مرة أخرى'],
            'Content_creators' => ['en' => 'Content Creators', 'ar' => 'صانعي المحتوى'],
            'creat_user_titel' => ['en' => 'Start your special journey', 'ar' => 'ابدأ رحلتك المميزة'],
            'creat_user_titel2' => ['en' => 'With the podcast', 'ar' => 'مع البودكاست'],
            'no_data_channal_titel' => ['en' => 'No channels created yet', 'ar' => 'لم يتم إنشاء قنوات بعد'],
            'no_data_channal_titel1' => ['en' => 'You can come back later, until channels are added by content creators', 'ar' => 'يمكنك العودة لاحقًا، لحين إضافة القنوات\nمن قبل صناع المحتوى'],
            'empty_name' => ['en' => 'Name is empty', 'ar' => 'الاسم فارغ'],
            'empty_email' => ['en' => 'Email is empty', 'ar' => 'البريد الالكتروني فارغ'],
            'error_email' => ['en' => 'Email is not valid', 'ar' => 'البريد الالكتروني غير سليم'],
            'empty_phone' => ['en' => 'Phone number is empty', 'ar' => 'الهاتف  فارغ'],
            'error_phone' => ['en' => 'Phone number is invalid', 'ar' => 'الهاتف  صحيح'],
            'error_confirmPassword' => ['en' => 'Passwords do not match', 'ar' => 'كلمة المرور غير متطابقه'],
            'empty_category' => ['en' => 'Category is empty', 'ar' => 'التصنيف فارغ'],
            'image_required' => ['en' => 'Image is required', 'ar' => 'الصوره مطلوبه'],
            'video_required' => ['en' => 'Video is required', 'ar' => 'الفيديو مطلوب'],
            'audio_required' => ['en' => 'Audio file is required', 'ar' => 'ملف الصوت مطلوب'],
            'empty_password' => ['en' => 'Password is empty', 'ar' => 'كلمة المرور  فارغه'],
            'empty_password_confirm' => ['en' => 'Password confirmation is empty', 'ar' => 'تاكيد كلمة المرور  فارغه'],
            'error_password_confirm' => ['en' => 'Passwords do not match', 'ar' => 'كلمة المرور غير مطابقه'],
            'do_you_logout' => ['en' => 'Do you really want to log out of the app? You will not receive any notifications upon logging out', 'ar' => 'هل تريد فعلا تسجيل الخروج من التطبيق؟ لن يصلك أي إشعارات عند قيامك بتسجيل الخروج'],
            'not_now' => ['en' => 'Not Now', 'ar' => 'ليس الآن'],
            'face' => ['en' => 'Facebook Account', 'ar' => 'حساب Facebook'],
            'x' => ['en' => 'X Account', 'ar' => 'حساب X'],
            'youtube' => ['en' => 'YouTube Account', 'ar' => 'حساب Youtube'],
            'snapchat' => ['en' => 'Snapchat Account', 'ar' => 'حساب Snapchat'],
            'instgram' => ['en' => 'Instagram Account', 'ar' => 'حساب Instgram'],
            'tiktok' => ['en' => 'TikTok Account', 'ar' => 'حساب tiktok'],
            'empty_filed' => ['en' => 'Field is empty', 'ar' => 'الحقل فارغ'],
            'add_season' => ['en' => 'Add Season', 'ar' => 'إضافة موسم'],
            'add_season_don' => ['en' => 'Season added successfully', 'ar' => 'تم غضافة الموسم بنجاح'],
            'add_a_season' => ['en' => 'Add a Season', 'ar' => 'إضافة الموسم'],
            'enter_season_name' => ['en' => 'Enter season name', 'ar' => 'أدخل اسم الموسم'],
            'channal_added' => ['en' => 'Channel added successfully', 'ar' => 'تم إضافة القناة بنجاح'],
            'sendded_sucsses' => ['en' => 'Sent successfully', 'ar' => 'تم الارسال بنجاح'],
            'profile_edited' => ['en' => 'Profile edited successfully', 'ar' => 'تم تعديل الملف الشخصي بنجاح'],
            'create_channel_done' => ['en' => 'Channel added successfully', 'ar' => 'تم إضافة القناة بنجاح'],
            'empty_season_titel1' => ['en' => 'You have not added any seasons yet', 'ar' => 'أنت لم تقم بإضافة مواسم بعد'],
            'empty_season_titel2' => ['en' => 'Add seasons now, so you can later link them to podcasts when adding new podcasts', 'ar' => 'أضف المواسم الآن، ليمكنك بعد ذلك ربطها  بالبودكاست عند إضافة بودكاست جديد'],
            'delete_season' => ['en' => 'Delete Season', 'ar' => 'حذف الموسم'],
            'delete_season_titel' => ['en' => 'Are you sure you want to delete this season?', 'ar' => 'هل أنت متأكد من حذف الموسم؟'],
            'empty_message' => ['en' => 'Messages are empty', 'ar' => 'الرسائل فارغه'],
            'no_data_favorites_titel1' => ['en' => 'You have not added any episodes to favorites', 'ar' => 'أنت لم تقم بإضافة حلقات في المفضلة'],
            'no_data_category_titel1' => ['en' => 'No categories added yet', 'ar' => 'لم يتم إضافة تصنيفات بعد'],
            'no_data_poscaster_titel1' => ['en' => 'No content creators currently', 'ar' => 'لا يوجد صناع محتوى حاليًا'],
            'no_data_poscaster_titel2' => ['en' => 'No content creators currently', 'ar' => 'لا يوجد صناع محتوى حاليًا'],
            'empty_podcasts_titel1' => ['en' => 'No episodes added yet', 'ar' => 'لم يتم اضافه اي حلقات حتي الان'],
            'empty_podcasts_titel2' => ['en' => 'No episodes added yet', 'ar' => 'لم يتم اضافه اي حلقات حتي الان'],
            'no_data_category_titel2' => ['en' => 'You can come back later until categories are added', 'ar' => 'يمكنك العودة لاحقًا، لحين إضافة التصنيفات'],
            'no_data_favorites_titel2' => ['en' => 'You can add your favorite episodes to favorites to return to them later, they will appear here if added', 'ar' => 'يمكنك وضع الحلقات التي أعجبتك في المفضلة، للعودة إليها لاحقًا، وستظهر هنا في حال إضافتها'],
            'Choose_video_type' => ['en' => 'Choose video type', 'ar' => 'اختر نوع الفديو'],
            'forget_pass_sucsses' => ['en' => 'Password successfully recovered', 'ar' => 'تم إستعادة كلمة المرور بنجاح'],
            'Enter_video_duration' => ['en' => 'Video Duration', 'ar' => 'مدة الفديو'],
            'link' => ['en' => 'Link', 'ar' => 'لينك'],
            'Category' => ['en' => 'Categories', 'ar' => 'التصنيفات'],
            'file' => ['en' => 'File', 'ar' => 'ملف'],
            'my_podcast' => ['en' => 'My Podcasts', 'ar' => 'حلقاتي'],
            'rate' => ['en' => 'Rate the Service', 'ar' => 'تقييم الخدمة'],
            'rate_page_titel' => ['en' => 'Choose your rating for the service', 'ar' => 'اختر من هنا تقييمك للخدمة'],
            'rate_page_titel_et' => ['en' => 'Write your opinion on the service, your opinion matters to us', 'ar' => 'اكتب هنا رأيك في الخدمة، لإن رأيك يهمنا'],
            'confirm_rate' => ['en' => 'Confirm Rating', 'ar' => 'تأكيد التقييم'],
            'empty_Choose_the_season' => ['en' => 'No season selected', 'ar' => 'لم يتم اختيار موسم'],
            'no_data_category_details_titel1' => ['en' => 'No episodes added to this category yet', 'ar' => 'لم يتم إضافة حلقات في هذا القسم بعد'],
            'no_data_category_details_titel2' => ['en' => 'You can come back later until episodes are added', 'ar' => 'يمكنك العودة لاحقًا، لحين إضافة الحلقات'],
            'empty_podcsts_titel1' => ['en' => 'No episodes added to this season yet', 'ar' => 'لم يتم إضافة حلقات في هذا الموسم بعد'],
            'empty_podcsts_titel2' => ['en' => 'You can come back later until episodes are added', 'ar' => 'يمكنك العودة لاحقًا، لحين إضافة الحلقات'],
            'no_data_notification_titel1' => ['en' => 'You have not received any notifications yet', 'ar' => 'لم يصلك أي إشعار بعد'],
            'no_data_notification_titel2' => ['en' => 'You will receive notifications here for new episodes added by content creators, and you can follow content creators if you have not followed any here', 'ar' => 'سيصلك هنا إشعارات بإضافة حلقة جديدة من قبل صانع المحتوى، ويمكنك متابعة صناع المحتوى إذا لم تقم بمتابعة أي صانع محتوى من هنا'],
            "show_all" => ["en" => "Show All", "ar" => "مشاهدة الكل"],
            "most_view" => ["en" => "Most Listened", "ar" => "الأكثر إستماعًا"],
            "new_podcasts" => ["en" => "Newly Released Episodes", "ar" => "حلقات أصدرت حديثًا"],
            "follow" => ["en" => "Follow", "ar" => "متابعه"],
            "about_podcaster" => ["en" => "About the Podcaster", "ar" => "نبذة عن صانع المحتوى"],
            "hallow" => ["en" => "Welcome", "ar" => "مرحبًا"],
            "coe_agein" => ["en" => "Welcome Back", "ar" => "بعودتك مرة أخرى"],
            "or_create_account" => ["en" => "Or Create a New Account", "ar" => "أو قم بإنشاء حساب جديد"],
            "create_normal_user" => ["en" => "Create Normal User Account", "ar" => "إنشاء حساب مستخدم عادي"],
            "creat_podcaster" => ["en" => "Create Podcaster Account", "ar" => "إنشاء حساب صانع محتوى"],
            "Enter_duration" => ["en" => "Duration", "ar" => "Duration"],
            "loading" => ["en" => "Loading", "ar" => "تحميل"]
        ];

        foreach ($mobile_keywords as $key => $keyword) {
            \App\Models\Keyword::create([
                'key' => $key,
                'value' => $keyword,
                'type' => 'mobile'
            ]);
        }


        $web_keywords = [
            'hello' => ['ar' => 'أهلا بك'],
            'welcome' => ['ar' => 'مرحبا'],
            'back' => ['ar' => 'بعودتك مرة اخرى'],
            'listen' => ['ar' => 'Listen'],
            'to_us_daily' => ['ar' => 'to us daily'],
            'google' => ['ar' => 'Google'],
            'apple' => ['ar' => 'Apple'],
            'home_audio_title' => ['ar' => 'كيف تبني عادة في 30 يومًا مع ليندا؟'],
            'home_audio_subtitle' => ['ar' => 'استمع للبودكاست الرئيسى'],
            'podcast_channels' => ['ar' => 'قنوات البودكاست'],
            'see_all' => ['ar' => 'مشاهدة الكل'],
            'all' => ['ar' => 'الكل'],
            'most_viewed_podcasts' => ['ar' => 'الحلقات الأكثر إستماعا'],
            'start_your_podcast_today' => ['ar' => 'لنبدأ البودكاست الخاص بك اليوم!'],
            'start_podcast_action_text' => ['ar' => 'كن بودكاستر'],
            'categories' => ['ar' => 'التصنيفات'],
            'most_recent' => ['ar' => 'الاحدث'],
            'users_comments' => ['ar' => 'تعليقات من المستخدمين'],
            'our_reviews' => ['ar' => 'شهاداتنا'],
            'our_philosophy' => ['ar' => 'فلسفتنا'],
            'articles_news' => ['ar' => 'اخبار و مقالات'],
            'download_app_now' => ['ar' => 'قم بتنزيل التطبيق الان'],
            'download_short_about' => ['ar' => 'بودكاستي هي المنصة الرائدة في تقديم المحتوى العربي حصرياً لمستمعيها <br> من خلال الموقع الالكتروني و تطبيق الهاتف الذكي.'],
            'have_any_question' => ['ar' => 'لديك اي استفسار ؟ تواصل معنا'],
            'contact_info' => ['ar' => 'بيانات التواصل'],
            'address' => ['ar' => 'العنوان'],
            'phone' => ['ar' => 'رقم الهاتف'],
            'email' => ['ar' => 'البريد الالكتروني'],
            'message' => ['ar' => 'الرسالة'],
            'send' => ['ar' => 'ارسال'],
            'submit' => ['ar' => 'ارسال'],
            'contact_us' => ['ar' => 'تواصل معنا'],
            'about_us' => ['ar' => 'من نحن'],
            'short_links' => ['ar' => 'روابط سريعة'],
            'home' => ['ar' => 'الرئيسية'],
            'channels' => ['ar' => 'القنوات'],
            'podcasts' => ['ar' => 'بودكاست'],
            'my_podcasts' => ['ar' => 'بودكاستاتى'],
            'episodes' => ['ar' => 'الحلقات'],
            'seasons' => ['ar' => 'مواسم'],
            'podcasters' => ['ar' => 'صانعو المحتوى'],
            'privacy_policy' => ['ar' => 'سياسة الخصوصية'],
            'terms_conditions' => ['ar' => 'الشروط والاحكام'],
            'footer_short_about' => ['ar' => 'منصة بودكاستي تقدم لكم عدد كبير و متنوع من البرامج التي من شأنها الارتقاء بمستوى الوعي والمعرفة من خلال تسليط الضوء على العديد من التحديات التي تواجه عالمنا اليوم، حيث يقوم بتقديم هذه البرامج نخبة من المذيعين المتألقين و الموهوبين.'],
            'search' => ['ar' => 'بحث'],
            'start_special_journey' => ['ar' => 'ابدأ رحلتلك المميزة'],
            'with_podcast' => ['ar' => 'مع البودكاست'],
            'register_now' => ['ar' => 'و سجل الان'],
            'publish_thoughts' => ['ar' => 'انشر جميع افكارك'],
            'as_podcaster' => ['ar' => 'كصانع محتوى'],
            'select_your_category' => ['ar' => 'اختر التصنيف الخاص بك'],
            'enter_email_phone' => ['ar' => 'ادخل البريد الالكترونى او رقم الجوال'],
            'enter_your_email' => ['ar' => 'ادخل البريد الالكترونى'],
            'enter_full_name' => ['ar' => 'ادخل اسمك بالكامل'],
            'enter_bio' => ['ar' => 'اكتب نبذة صغيره عنك'],
            'enter_phone' => ['ar' => 'ادخل رقم الهاتف'],
            'enter_pwd' => ['ar' => 'ادخل كلمة المرور'],
            'new_pwd' => ['ar' => 'كلمة المرور الجديدة'],
            'reset_pwd' => ['ar' => 'اعادة تعيين كلمة المرور'],
            'current_pwd' => ['ar' => 'كلمة المرور الحالية'],
            'forgot_pwd' => ['ar' => 'نسيت كلمة المرور ؟'],
            'confirm_pwd' => ['ar' => 'تأكيد كلمة المرور'],
            'agree_terms_conditions' => ['ar' => 'أوافق على الشروط والاحكام'],
            'already_have_account' => ['ar' => 'امتلك حساب بالفعل'],
            'login' => ['ar' => 'تسجيل الدخول'],
            'logout' => ['ar' => 'تسجيل الخروج'],
            'save' => ['ar' => 'حفظ'],
            'or_create_account' => ['ar' => 'أو قم بإنشاء حساب جديد'],
            'create_account' => ['ar' => 'إنشاء حساب'],
            'create_new_account' => ['ar' => 'انشاء حساب جديد'],
            'create_podcaster_account' => ['ar' => 'إنشاء حساب صانع محتوى'],
            'create_user_account' => ['ar' => 'إنشاء حساب مستخدم عادى'],
            'no_seasons_found' => ['ar' => 'لم يتم اضافة مواسم حتي الان'],
            'no_favourites_found' => ['ar' => 'لم يتم اضافة حلقات في المفضلة'],
            'no_category_podcasts_found' => ['ar' => 'لم يتم اضافة حلقات في هذه الفئة حتي الان'],
            'no_podcasts_found' => ['ar' => 'لا توجد حلقات'],
            'no_results_found' => ['ar' => 'لا توجد نتائج'],
            'otp_email_sent' => ['ar' => 'تم ارسال الكود الخاص بك عبر الايميل'],
            'profile_updated' => ['ar' => 'تم تعديل الملف الشخصي بنجاح'],
            'success' => ['ar' => 'تم بنجاح'],
            'error_occurred' => ['ar' => 'حدث خطأ ما'],
            'about_mission_1' => ['ar' => 'مهمة'],
            'about_mission_2' => ['ar' => 'رؤية'],
            'about_mission_3' => ['ar' => 'قيم'],
            'follow' => ['ar' => 'متابعة'],
            'unfollow' => ['ar' => 'الغاء المتابعة'],
            'followers' => ['ar' => 'متابع'],
            'profile' => ['ar' => 'الملف الشخصى'],
            'my_favourite' => ['ar' => 'مفضلتى'],
            'wrong_curr_pwd' => ['ar' => 'كلمة المرور الحالية غير صحيحة'],
            'enter_otp' => ['ar' => 'ادخل الكود'],
            'invalid_otp' => ['ar' => 'رمز التحقق غير صحيح'],
            'pwd_updated' => ['ar' => 'تم تغيير كلمة السر بنجاح'],

            'show_more' => ['ar' => 'عرض المزيد'],
            'other_articles' => ['ar' => 'مقالات أخري'],
            'contact_us_msg' => ['ar' => 'شكرًا لتواصلك معنا. سنعاود الاتصال بك قريبًا.'],
            'register_success_msg' => ['ar' => 'شكرًا لانضمامك إلينا.'],
            'ok' => ['ar' => 'حسناً'],
            'meta_title' => ['ar' => 'عنوان المنصة'],
            'meta_description' => ['ar' => 'وصف المنصة'],
            'notifications' => ['ar' => 'الاشعارات'],
            'no_notifications' => ['ar' => 'لا توجد اشعارات'],

            'sort_by' => ['ar' => 'ترتيب حسب'],
            'comments' => ['ar' => 'التعليقات'],
            'latest' => ['ar' => 'الأحدث'],
            'oldest' => ['ar' => 'الأقدم'],
            'edit' => ['ar' => 'تعديل'],
            'delete' => ['ar' => 'حذف'],
            'write_comment' => ['ar' => 'اكتب تعليقك هنا'],
            'add_comment' => ['ar' => 'اضافة تعليق'],
            'cancel' => ['ar' => 'الغاء'],
            'load_more' => ['ar' => 'عرض المزيد'],

        ];


        foreach ($web_keywords as $key => $keyword) {
            \App\Models\Keyword::create([
                'key' => $key,
                'value' => $keyword,
                'type' => 'web'
            ]);
        }

    }
}
